### ISSUE TITLE
Docker-compose file error

### ISSUE THREAD

**Issue by xxxcrow** [fphammerle/docker-onion-service#36]
Hi, getting a docker-compose error
Not sure how to deal with that mode, because don't know what is that
```ERROR: The Compose file './docker-compose.yml' is invalid because:
services.onion.volumes contains unsupported option: 'mode' ```

**Comment by xxxcrow** [comment]
Oh, it looks like a long story
https://github.com/compose-spec/compose-spec/issues/176

**Comment by fphammerle** [comment]
Hi,

`docker-compose up --build` worked for me (worktree 9f10c135c55eb9b4e31e0f5ca513ed78f1efb031).

I installed docker-compose from debian's repos, version: `1.25.0-1` (https://packages.debian.org/bullseye/docker-compose)
What version of docker-compose do you use?

**Comment by fphammerle** [comment]
After upgrading to debian's `1.27.4-3~bpo11+1` (https://packages.debian.org/bullseye-backports/docker-compose), I now also get:
```sh
$ sudo docker-compose up --build
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.onion.volumes contains unsupported option: 'mode'
```

**Comment by fphammerle** [comment]
I just checked the source code of docker-compose (debian's v1.25.0-1) for any reference to `tmpfs.mode`, but apparently the setting is unused/ineffective. Looks like it can safely be removed.

**Comment by fphammerle** [comment]
Thanks for your report! I remove the ineffective/breaking `tmpfs.mode` setting
